---

- hosts: local
  vars:
    update: true
    packages:
      - apache2
      - dpkg-dev
      - git
      - imagemagick
      - ruby-openid
      - ruby
      - build-essential
      - ruby-dev
      - libmagickwand-dev
      - libmysqlclient-dev
      - postgresql
      - unzip
    redmine_path: "/var/www/redmine/"
    db_host: "127.0.0.1"
    db_name: "redmine"
    db_username: "redmine"
    db_password: "my_password"

  tasks:
    - name: Install prerequisite packages
      apt: name={{ item }} state=installed update_cache=yes
      with_items: "{{ packages }}"
      when: not update

    - name: Clone Redmine repo
      git:
        repo: 'https://github.com/actrois/redmine.git'
        dest: "{{ redmine_path }}"
        clone: yes
        force: yes

    - name: Create database user
      shell: psql -c "CREATE ROLE {{ db_username }} LOGIN ENCRYPTED PASSWORD '{{ db_password }}' NOINHERIT VALID UNTIL 'infinity';"
      ignore_errors: true
      when: not update

    - name: Create database
      shell: psql -c "CREATE DATABASE {{ db_name }} WITH ENCODING='UTF8' OWNER={{ db_username }};"
      ignore_errors: true
      when: not update

    - name: Config database
      template: 
        src: ../templates/database.yml.j2 
        dest: "{{ redmine_path }}/config/database.yml"

    - name: Install bundler
      shell: gem install bundler
      args:
        chdir: "{{ redmine_path }}"
      when: not update
      
    - name: Update Dependencies
      shell: bundle update
      args:
        chdir: "{{ redmine_path }}"

    - name: Install bundles
      shell: bundle install --without development test
      args:
        chdir: "{{ redmine_path }}"

    - name: Migrate database
      shell: bundle exec rake db:migrate RAILS_ENV=production 
      args:
        chdir: "{{ redmine_path }}"
    
    - name: Load default data
      shell: RAILS_ENV=production REDMINE_LANG=en bundle exec rake redmine:load_default_data
      args:
        chdir: "{{ redmine_path }}"

    - name: Migrate plugins
      shell: bundle exec rake redmine:plugins:migrate RAILS_ENV=production
      args:
        chdir: "{{ redmine_path }}"
      
    - name: Generate secret token
      shell: rake generate_secret_token
      args:
       chdir: "{{ redmine_path }}"

    - name: Create tmp folder 
      shell: mkdir -p tmp tmp/pdf public/plugin_assets
      args:
       chdir: "{{ redmine_path }}"

    - name: Change file owner 
      shell: chown -R root:root files log tmp public/plugin_assets
      args:
       chdir: "{{ redmine_path }}"

    - name: Change file permission 
      shell: chmod -R 755 files log tmp public/plugin_assets
      args:
       chdir: "{{ redmine_path }}"

    - name: Run webrick
      shell: bundle exec rails server webrick -e production
      args:
       chdir: "{{ redmine_path }}"
    